Feature /student notas
Edge-Academy-UFAL/student-manager-ui pull request #25
Opened 2024-05-15 18:04 UTC by rafaelrlc

Tabela de notas do student:

![image](https://github.com/Edge-Academy-UFAL/student-manager-ui/assets/105018495/f7ceaa28-72e7-4d6a-a11e-652bf4e2020f)

Modal de adicionar:

![image](https://github.com/Edge-Academy-UFAL/student-manager-ui/assets/105018495/20592b4a-ba5d-4b2b-9dd2-9e2907d8f3c2)

Modal de edição de nota:

![image](https://github.com/Edge-Academy-UFAL/student-manager-ui/assets/105018495/501f9bae-546d-4000-bcef-da533dd2f100)

Modal de remoção de nota:

![image](https://github.com/Edge-Academy-UFAL/student-manager-ui/assets/105018495/8085535d-7043-4c0d-8aee-a26ec1a96a7e)

Até o momento apenas o modal de adicionar foi implementado com a API, estou no aguardo para poder implementar o resto. Foi feito validação em todos os campos.

Por agora, por razões de simplicidade não vou utilizar server-actions para ter um feedback instantaneo da API, ao adicionar, remover e editar notas. Por agora o usuário terá que da F5 para visualizar as mudanças.

2024-05-16 23:03 UTC, Arthurpmrs requested changes
Alguns pequenos ajustes:

1. Ao renderizar os botões de Adicionar, Editar e Deletar uma nota do aluno, checar se o aluno logado é o mesmo da página. Efetivamente o que isso vai garantir é que ninguém mais possa editar as notas. _Isso vai ser revisto quando tivermos clareza sobre o que cada Role pode fazer._
2. Permitir que o aluno adicione uma disciplina sem nota, para o caso de estar cursando.
3. Trocar o header da coluna da tabela de notas de "Status" para "Situação" (estamos deixando tudo em português). Além disso, ao passar o hover no header da tabela, o espaço da última cédula não muda de cor.

2024-05-17 11:30 UTC, daviromao approved these changes
Um gênio!

![image](https://github.com/Edge-Academy-UFAL/student-manager-ui/assets/53953664/c006a3ec-5ae8-4602-a5bd-4704170e8444)

2024-05-17 14:50 UTC, rafaelrlc commented
> Alguns pequenos ajustes:
> 
> 1. Ao renderizar os botões de Adicionar, Editar e Deletar uma nota do aluno, checar se o aluno logado é o mesmo da página. Efetivamente o que isso vai garantir é que ninguém mais possa editar as notas. _Isso vai ser revisto quando tivermos clareza sobre o que cada Role pode fazer._
> 2. Permitir que o aluno adicione uma disciplina sem nota, para o caso de estar cursando.
> 3. Trocar o header da coluna da tabela de notas de "Status" para "Situação" (estamos deixando tudo em português). Além disso, ao passar o hover no header da tabela, o espaço da última cédula não muda de cor.

Feito

2024-05-17 16:16 UTC, Arthurpmrs approved these changes
Show de pelota!

2024-05-17 16:17 UTC, merged